name: "Staging->GH-Pages"

on:
  push:
    branches: [staging]
  workflow_dispatch:

jobs:
  build-staging:
    name: build and push to gh-pages
    uses: Xananax/godot-ci-test/.github/workflows/BuildGodot.yaml@github-actions-v1.1
    with:
      sub_build_path: /staging
      watermark: $GITHUB_REPOSITORY:$GITHUB_WORKFLOW:$GITHUB_REF_NAME:$GITHUB_SHA